# Project info
site_name: The Automation Hub
site_description: 'Documentation, guides and articles on creating, developing and implementing automated betting strategies, using data analysis to inform betting models and how to interact with the Betfair API.'
site_author: 'Betfair Data Scientists'
site_url: 'https://betfair-datascientists.github.io'
docs_dir: 'src'
site_dir: 'docs'

# Navigation
nav:
    - Home: index.md

    - Getting Started:
        - Getting Started with Betfair: gettingStarted/betfairHowTo.md
        - Betting Glossary: gettingStarted/bettingGlossary.md
        - Commission and Charges: gettingStarted/commission.md
        - Value and Odds: gettingStarted/valueAndOdds.md
        - Staking Methods and Bankroll Management: gettingStarted/stakingMethods.md
        - Cashback 2nd Markets: gettingStarted/2ndPlaceVoid.md
        - Exactas & Quinella: gettingStarted/exactaQuinella.md

    - Betfair Data: 
        - CSV Files: data/dataListing.md
        - Historic Data Site: data/usingHistoricDataSite.md
        - Making Sense of the Stream Files: data/historicStreamFiles.md
        - Processing TAR Files Efficiently: data/processingTarFiles101.ipynb
        - Converting JSON Stream Data to CSV: data/jsonToCsvRevisited/index.md

    - Betfair API:
        - API resources: api/apiResources.md
        - Betfair Australia - How to access the Betfair API: api/apiappkey.md
        - Betfair API Tutorial (R): api/apiRtutorial.md
        - Betfair API Tutorial (Python): api/apiPythontutorial.md
            
    - Modelling:
#        - Datathon:
#            - FIFA World Cup Datathon: modelling/worldCupDatathon.md
        - Foundations:
            - Introduction to Modelling: modelling/howToModel.md
            - Pricing Data Sources: modelling/dataSources.md
            - Cloud vs Local Machines: modelling/cloudOrLocalMachine.md
            - Monte Carlo Simulations: modelling/monteCarloSimulations.md

        - AFL:
            - Player Disposal Lines: modelling/AFLPlayerDisposalsTutorial.md
            - Betting Player Disposal Markets: modelling/AFLPlayerDisposalsFlumine.md
            - How a Data Scientist Models the Brownlow: modelling/modellingTheBrownlowMedal.md

            - Legacy Tutorials:
                - AFL Modelling Walkthrough (Python): modelling/AFLmodellingPython.md
                - Modelling the Brownlow Medal (Python): modelling/brownlowModelTutorial.ipynb

        - Greyhounds:
            - Greyhound Topaz API (Python): modelling/topazTutorial.md

            - Legacy Tutorials:
                - Greyhound FastTrack API (Python): modelling/fasttrackTutorial.ipynb
                - Greyhound Modelling (Python): modelling/greyhoundModellingPython.ipynb

        - Soccer:
            - Building a Soccer Bot — Part 1: modelling/howToBuildASoccerBotPartI.md
            - Building a Soccer Bot — Part 2: modelling/howToBuildASoccerBotPartII.md
            - Building a Soccer Bot — Part 3: modelling/howToBuildASoccerBotPartIII.md

            - Legacy Tutorials:
                - Soccer Modelling (Python): modelling/soccerModellingTutorialPython.md
                - EPL Machine Learning (Python): modelling/EPLmlPython.md
                - Soccer Modelling for the 2022 FIFA World Cup (R): modelling/soccerModellingELO2022WorldCup.md
                - Elo Soccer Tutorial (R): modelling/soccerEloTutorialR.md
                - Soccer Modelling (R): modelling/soccerModellingTutorialR.md

        - Tennis:
            - Legacy Tutorials:
                - How to Model the Australian Open: modelling/howToModelTheAusOpen.md
                - Australian Open Tutorial (R): modelling/AusOpenRTutorial.md
                - Australian Open Tutorial (Python): modelling/AusOpenPythonTutorial.md

    - Automation & Backtesting:
        - Foundations:
            - Golden Rules of Automation: tutorials/goldenRulesOfAutomation.md

        - Automation Series:
            - How to Automate — Part 1: tutorials/How_to_Automate_1.ipynb
            - How to Automate — Part 2: tutorials/How_to_Automate_2.ipynb
            - How to Automate — Part 3: tutorials/How_to_Automate_3.ipynb
            - How to Automate — Part 4: tutorials/How_to_Automate_4.md
            - How to Automate — Part 5: tutorials/How_to_Automate_5.md

        - Backtesting:
            - Hub Predictions Model: tutorials/hubPredictionsModel.md
            - Back testing ratings in Python: tutorials/backtestingRatingsTutorial.md
            - Flumine Simulations: tutorials/flumineSimulations.md

        - Data & Logging:
            - Flumine Results to CSV Files: tutorials/resultsLoggingTutorial.md

        - Strategy Automation:
            - Automated Betting Angles in Python: tutorials/automatedBettingAnglesTutorial.ipynb

        - Market Analysis:
            - Understanding Market Formation and Price Movement: tutorials/analysingAndPredictingMarketMovements.ipynb
            - Understanding BSP and Market Efficiency: tutorials/analysingAndPredictingBSP.ipynb

    - Mental Game:
        - Intro: mentalGame/intro.md
        - The Role of Emotions in Wagering: mentalGame/roleOfEmotions.md
        - Map Your Emotions: mentalGame/mapYourEmotions.md
        - Handling Variance: mentalGame/handlingBadVariance.md
        - Win By Being Great At Losing: mentalGame/winbyBeingGreatatLosing.md
        - Correcting Your Emotions: mentalGame/correctingyouremotions.md
        - Responsible Gambling: mentalGame/responsibleGambling.md
        - Maximize Your Learning with the Inchworm Concept: mentalGame/InchwormConcept.md
        - The High Cost of High Expectations: mentalGame/HighExpectations.md
        - Tapping Your Intuition: mentalGame/TappingYourIntuition.md

# Theme settings
theme:
    name: material
    custom_dir: 'theme'
    favicon: 'img/BetfairFavicon.ico'
    logo: 'img/logo.svg'
    language: 'en'
    palette:
        -   scheme: betfair
            primary: amber
            accent: orange
            media: "(prefers-color-scheme: light)" 
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   scheme: slate
            primary: amber
            accent: orange
            media: "(prefers-color-scheme: dark)" 
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode
    font:
        text: 'Roboto'
        code: 'Roboto Mono' 
    features:
        - toc.integrate
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.expand
        - navigation.sections
        - search.suggest
        - search.highlight
        - search.share
 
# Extensions
markdown_extensions:
    - admonition
    - meta
    - md_in_html
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences

# plugins
plugins:
   - search
   - mknotebooks

extra:
    rg_footer: '<div class="full-screen">
  <p style="font-family: Arial, sans-serif; font-size: 1.2rem; font-weight: bold; text-align: center;">Chances are you&#39re about to lose.</p>
  <p style="font-family: Arial, sans-serif; font-size: 0.8rem; font-weight: bold; text-align: center;">For free and confidential support call 1800 858 858 or visit <a href="http://www.gamblinghelponline.org.au" style="color: black; text-decoration: underline;">gamblinghelponline.org.au</a></p>
    </div>'

    generator: false
    # Social Media links (footer)
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/Betfair_Aus
        - icon: fontawesome/brands/linkedin
          link: https://linkedin.com/company/betfair-australia
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/betfairaustralia
        - icon: fontawesome/brands/youtube
          link: https://youtube.com/user/betfairaus
        - icon: fontawesome/brands/github
          link: https://github.com/betfair-datascientists
    # Google Analytics
    analytics:
        provider: google
        property: UA-125973915-1

# betfair custom theme css file
extra_css:
    - assets/stylesheets/betfair.css
    - css/buttons_and_animations.css
    - css/fonts.css

extra_javascript:
    - js/scripts.js